import type { FieldMap } from '../types.js'
import type { InfoboxType } from '../types.js'

/** A composed value receives the suffix string ('' for the base block, '2', '3', … inside repeat sections). */
export type InfoboxRowSpec = {
	label: string
	keys?: string[]
	compose?: (fields: FieldMap, suffix: string) => string
	/** Default label/value to use when the resolved label is empty. Only meaningful inside a repeat section's discoverable rows. */
	fallbackLabel?: string
}

export type StaticSection = {
	heading?: string
	rows: InfoboxRowSpec[]
}

/**
 * Repeating section pattern: discover blocks by checking `discoverKey`, `${discoverKey}1`, … up to `max`.
 * Each discovered block becomes one section. The section heading is the value of the discover key
 * for that block. Row `keys` and `compose(_, suffix)` inside the section get the current suffix appended/passed.
 */
export type RepeatSection = {
	repeat: {
		discoverKey: string
		max: number
	}
	rows: InfoboxRowSpec[]
}

export type InfoboxSection = StaticSection | RepeatSection

export type InfoboxSchema = {
	id: InfoboxType
	title: string[]
	/** Overrides title resolution when present. */
	titleCompose?: (fields: FieldMap) => string
	subtitle?: string[]
	image: string[]
	caption: string[]
	sections: InfoboxSection[]
	/** Extra keys that the schema consumes via `compose` or `titleCompose`; excluded from the fallback list. */
	extraKeys?: string[]
}

export function isRepeatSection(section: InfoboxSection): section is RepeatSection {
	return 'repeat' in section
}

/**
 * Compute the set of field keys the schema consumes, including all suffixed variants
 * generated by repeat sections. Used to filter the fallback "remaining fields" list.
 */
export function knownKeys(schema: InfoboxSchema): Set<string> {
	const out = new Set<string>()
	const add = (key: string) => out.add(key.toLowerCase())
	const addWithSuffix = (key: string, max: number) => {
		add(key)
		for (let index = 1; index <= max; index++) add(`${key}${index}`)
	}

	for (const key of schema.title) add(key)
	for (const key of schema.subtitle ?? []) add(key)
	for (const key of schema.image) add(key)
	for (const key of schema.caption) add(key)
	for (const key of schema.extraKeys ?? []) add(key)

	for (const section of schema.sections) {
		if (isRepeatSection(section)) {
			const max = section.repeat.max
			addWithSuffix(section.repeat.discoverKey, max)
			for (const row of section.rows) {
				for (const key of row.keys ?? []) addWithSuffix(key, max)
			}
		} else {
			for (const row of section.rows) {
				for (const key of row.keys ?? []) add(key)
			}
		}
	}
	return out
}
