-- Seed template for world map MVP.
-- 1) Insert countries and optional links to /know pages.
-- 2) Insert a map row.
-- 3) Insert hex-region assignments.
-- 4) Insert vector paths generated by the ingest pipeline.

-- Countries
INSERT INTO countries (name, slug, page_slug, capital, governance, color)
VALUES
	('Oncheran Empire', 'oncheran-empire', 'Oncheran_Empire', 'Onchera', 'Empire', '#C9483A'),
	('Velan Confederacy', 'velan-confederacy', 'Velan_Confederacy', 'Velis', 'Confederacy', '#2F7F9D')
ON CONFLICT (slug) DO NOTHING;

-- World map metadata
INSERT INTO world_maps (name, slug, image_filename, image_width, image_height, water_hex, description)
VALUES
	('Main World Map', 'main-world-map', 'main-world-equirect.png', 4096, 2048, '#000000', 'Primary political map for the world setting')
ON CONFLICT (slug) DO NOTHING;

-- Color assignments to countries
WITH map_ref AS (
	SELECT id FROM world_maps WHERE slug = 'main-world-map'
),
country_refs AS (
	SELECT id, slug FROM countries WHERE slug IN ('oncheran-empire', 'velan-confederacy')
)
INSERT INTO world_map_regions (map_id, country_id, hex_color, label)
SELECT map_ref.id, country_refs.id, data.hex_color, data.label
FROM map_ref
JOIN country_refs ON country_refs.slug = data.country_slug
JOIN (
	VALUES
		('oncheran-empire', '#C9483A', 'Oncheran Empire'),
		('velan-confederacy', '#2F7F9D', 'Velan Confederacy')
) AS data(country_slug, hex_color, label)
ON true
ON CONFLICT (map_id, hex_color) DO NOTHING;

-- Geometry placeholders (replace with generated paths from PNG vectorization)
WITH region_ref AS (
	SELECT r.id
	FROM world_map_regions r
	JOIN world_maps m ON m.id = r.map_id
	WHERE m.slug = 'main-world-map' AND r.hex_color = '#C9483A'
)
INSERT INTO world_map_region_geometry (region_id, path_data, sort_order)
SELECT region_ref.id, 'M 100 100 L 300 100 L 300 280 L 100 280 Z', 0
FROM region_ref
ON CONFLICT DO NOTHING;
